name: PHPUnit

on:

  push:
    branches: [master]

  pull_request:

permissions:

  contents: read

jobs:

  tests:
    name: PHPUnit

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - '7.0'
          - '7.1'
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
        dependencies:
          - ''
          - '--prefer-lowest'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer

      - name: Validate composer.json
        run: composer validate --strict

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer update --ansi --no-interaction --no-progress --prefer-dist ${{ matrix.dependencies }}

      - name: Run unit tests
        run: vendor/bin/phpunit
